/**
 * Rakam API Documentation
 * An analytics platform API that lets you create your own analytics services.
 *
 * OpenAPI spec version: 0.5
 * Contact: contact@rakam.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'client.model/Library', 'client.model/MappingPlugin'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Library'), require('./MappingPlugin'));
  } else {
    // Browser globals (root is window)
    if (!root.RakamClient) {
      root.RakamClient = {};
    }
    root.RakamClient.EventContext = factory(root.RakamClient.ApiClient, root.RakamClient.Library, root.RakamClient.MappingPlugin);
  }
}(this, function(ApiClient, Library, MappingPlugin) {
  'use strict';




  /**
   * The EventContext model module.
   * @module client.model/EventContext
   * @version 0.5
   */

  /**
   * Constructs a new <code>EventContext</code>.
   * @alias module:client.model/EventContext
   * @class
   * @param apiKey {String} 
   * @param library {module:client.model/Library} 
   * @param apiVersion {String} 
   * @param uploadTime {Integer} 
   * @param checksum {String} 
   * @param plugins {Array.<module:client.model/MappingPlugin>} 
   */
  var exports = function(apiKey, library, apiVersion, uploadTime, checksum, plugins) {
    var _this = this;

    _this['api_key'] = apiKey;
    _this['library'] = library;
    _this['api_version'] = apiVersion;
    _this['upload_time'] = uploadTime;
    _this['checksum'] = checksum;
    _this['plugins'] = plugins;
  };

  /**
   * Constructs a <code>EventContext</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:client.model/EventContext} obj Optional instance to populate.
   * @return {module:client.model/EventContext} The populated <code>EventContext</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('api_key')) {
        obj['api_key'] = ApiClient.convertToType(data['api_key'], 'String');
      }
      if (data.hasOwnProperty('library')) {
        obj['library'] = Library.constructFromObject(data['library']);
      }
      if (data.hasOwnProperty('api_version')) {
        obj['api_version'] = ApiClient.convertToType(data['api_version'], 'String');
      }
      if (data.hasOwnProperty('upload_time')) {
        obj['upload_time'] = ApiClient.convertToType(data['upload_time'], 'Integer');
      }
      if (data.hasOwnProperty('checksum')) {
        obj['checksum'] = ApiClient.convertToType(data['checksum'], 'String');
      }
      if (data.hasOwnProperty('plugins')) {
        obj['plugins'] = ApiClient.convertToType(data['plugins'], [MappingPlugin]);
      }
    }
    return obj;
  }

  /**
   * @member {String} api_key
   */
  exports.prototype['api_key'] = undefined;
  /**
   * @member {module:client.model/Library} library
   */
  exports.prototype['library'] = undefined;
  /**
   * @member {String} api_version
   */
  exports.prototype['api_version'] = undefined;
  /**
   * @member {Integer} upload_time
   */
  exports.prototype['upload_time'] = undefined;
  /**
   * @member {String} checksum
   */
  exports.prototype['checksum'] = undefined;
  /**
   * @member {Array.<module:client.model/MappingPlugin>} plugins
   */
  exports.prototype['plugins'] = undefined;



  return exports;
}));


