/**
 * Rakam API Documentation
 * An analytics platform API that lets you create your own analytics services.
 *
 * OpenAPI spec version: 0.5
 * Contact: contact@rakam.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.RakamClient) {
      root.RakamClient = {};
    }
    root.RakamClient.EventFilterAggregation = factory(root.RakamClient.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The EventFilterAggregation model module.
   * @module client.model/EventFilterAggregation
   * @version 0.5
   */

  /**
   * Constructs a new <code>EventFilterAggregation</code>.
   * @alias module:client.model/EventFilterAggregation
   * @class
   */
  var exports = function() {
    var _this = this;





  };

  /**
   * Constructs a <code>EventFilterAggregation</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:client.model/EventFilterAggregation} obj Optional instance to populate.
   * @return {module:client.model/EventFilterAggregation} The populated <code>EventFilterAggregation</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('field')) {
        obj['field'] = ApiClient.convertToType(data['field'], 'String');
      }
      if (data.hasOwnProperty('minimum')) {
        obj['minimum'] = ApiClient.convertToType(data['minimum'], 'Integer');
      }
      if (data.hasOwnProperty('maximum')) {
        obj['maximum'] = ApiClient.convertToType(data['maximum'], 'Integer');
      }
      if (data.hasOwnProperty('type')) {
        obj['type'] = ApiClient.convertToType(data['type'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} field
   */
  exports.prototype['field'] = undefined;
  /**
   * @member {Integer} minimum
   */
  exports.prototype['minimum'] = undefined;
  /**
   * @member {Integer} maximum
   */
  exports.prototype['maximum'] = undefined;
  /**
   * @member {module:client.model/EventFilterAggregation.TypeEnum} type
   */
  exports.prototype['type'] = undefined;


  /**
   * Allowed values for the <code>type</code> property.
   * @enum {String}
   * @readonly
   */
  exports.TypeEnum = {
    /**
     * value: "COUNT"
     * @const
     */
    "COUNT": "COUNT",
    /**
     * value: "COUNT_UNIQUE"
     * @const
     */
    "COUNT_UNIQUE": "COUNT_UNIQUE",
    /**
     * value: "SUM"
     * @const
     */
    "SUM": "SUM",
    /**
     * value: "MINIMUM"
     * @const
     */
    "MINIMUM": "MINIMUM",
    /**
     * value: "MAXIMUM"
     * @const
     */
    "MAXIMUM": "MAXIMUM",
    /**
     * value: "AVERAGE"
     * @const
     */
    "AVERAGE": "AVERAGE",
    /**
     * value: "APPROXIMATE_UNIQUE"
     * @const
     */
    "APPROXIMATE_UNIQUE": "APPROXIMATE_UNIQUE"  };


  return exports;
}));


