/**
 * Rakam API Documentation
 * An analytics platform API that lets you create your own analytics services.
 *
 * OpenAPI spec version: 0.5
 * Contact: contact@rakam.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'client.model/EventFilterAggregation', 'client.model/Timeframe'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./EventFilterAggregation'), require('./Timeframe'));
  } else {
    // Browser globals (root is window)
    if (!root.RakamClient) {
      root.RakamClient = {};
    }
    root.RakamClient.EventFilter = factory(root.RakamClient.ApiClient, root.RakamClient.EventFilterAggregation, root.RakamClient.Timeframe);
  }
}(this, function(ApiClient, EventFilterAggregation, Timeframe) {
  'use strict';




  /**
   * The EventFilter model module.
   * @module client.model/EventFilter
   * @version 0.5
   */

  /**
   * Constructs a new <code>EventFilter</code>.
   * @alias module:client.model/EventFilter
   * @class
   */
  var exports = function() {
    var _this = this;





  };

  /**
   * Constructs a <code>EventFilter</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:client.model/EventFilter} obj Optional instance to populate.
   * @return {module:client.model/EventFilter} The populated <code>EventFilter</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('collection')) {
        obj['collection'] = ApiClient.convertToType(data['collection'], 'String');
      }
      if (data.hasOwnProperty('timeframe')) {
        obj['timeframe'] = Timeframe.constructFromObject(data['timeframe']);
      }
      if (data.hasOwnProperty('aggregation')) {
        obj['aggregation'] = EventFilterAggregation.constructFromObject(data['aggregation']);
      }
      if (data.hasOwnProperty('filterExpression')) {
        obj['filterExpression'] = ApiClient.convertToType(data['filterExpression'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} collection
   */
  exports.prototype['collection'] = undefined;
  /**
   * @member {module:client.model/Timeframe} timeframe
   */
  exports.prototype['timeframe'] = undefined;
  /**
   * @member {module:client.model/EventFilterAggregation} aggregation
   */
  exports.prototype['aggregation'] = undefined;
  /**
   * @member {String} filterExpression
   */
  exports.prototype['filterExpression'] = undefined;



  return exports;
}));


