/**
 * Rakam API Documentation
 * An analytics platform API that lets you create your own analytics services.
 *
 * OpenAPI spec version: 0.5
 * Contact: contact@rakam.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'client.model/FunnelStep', 'client.model/FunnelWindow'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./FunnelStep'), require('./FunnelWindow'));
  } else {
    // Browser globals (root is window)
    if (!root.RakamClient) {
      root.RakamClient = {};
    }
    root.RakamClient.FunnelQuery = factory(root.RakamClient.ApiClient, root.RakamClient.FunnelStep, root.RakamClient.FunnelWindow);
  }
}(this, function(ApiClient, FunnelStep, FunnelWindow) {
  'use strict';




  /**
   * The FunnelQuery model module.
   * @module client.model/FunnelQuery
   * @version 0.5
   */

  /**
   * Constructs a new <code>FunnelQuery</code>.
   * @alias module:client.model/FunnelQuery
   * @class
   */
  var exports = function() {
    var _this = this;






  };

  /**
   * Constructs a <code>FunnelQuery</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:client.model/FunnelQuery} obj Optional instance to populate.
   * @return {module:client.model/FunnelQuery} The populated <code>FunnelQuery</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('steps')) {
        obj['steps'] = ApiClient.convertToType(data['steps'], [FunnelStep]);
      }
      if (data.hasOwnProperty('dimension')) {
        obj['dimension'] = ApiClient.convertToType(data['dimension'], 'String');
      }
      if (data.hasOwnProperty('startDate')) {
        obj['startDate'] = ApiClient.convertToType(data['startDate'], 'Date');
      }
      if (data.hasOwnProperty('window')) {
        obj['window'] = FunnelWindow.constructFromObject(data['window']);
      }
      if (data.hasOwnProperty('endDate')) {
        obj['endDate'] = ApiClient.convertToType(data['endDate'], 'Date');
      }
    }
    return obj;
  }

  /**
   * @member {Array.<module:client.model/FunnelStep>} steps
   */
  exports.prototype['steps'] = undefined;
  /**
   * @member {String} dimension
   */
  exports.prototype['dimension'] = undefined;
  /**
   * @member {Date} startDate
   */
  exports.prototype['startDate'] = undefined;
  /**
   * @member {module:client.model/FunnelWindow} window
   */
  exports.prototype['window'] = undefined;
  /**
   * @member {Date} endDate
   */
  exports.prototype['endDate'] = undefined;



  return exports;
}));


