/**
 * Rakam API Documentation
 * An analytics platform API that lets you create your own analytics services.
 *
 * OpenAPI spec version: 0.5
 * Contact: contact@rakam.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.RakamClient) {
      root.RakamClient = {};
    }
    root.RakamClient.OLAPTable = factory(root.RakamClient.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The OLAPTable model module.
   * @module client.model/OLAPTable
   * @version 0.5
   */

  /**
   * Constructs a new <code>OLAPTable</code>.
   * @alias module:client.model/OLAPTable
   * @class
   * @param collections {Array.<String>} 
   * @param dimensions {Array.<String>} 
   * @param aggregations {Array.<module:client.model/OLAPTable.AggregationsEnum>} 
   * @param measures {Array.<String>} 
   * @param tableName {String} 
   */
  var exports = function(collections, dimensions, aggregations, measures, tableName) {
    var _this = this;

    _this['collections'] = collections;
    _this['dimensions'] = dimensions;
    _this['aggregations'] = aggregations;
    _this['measures'] = measures;
    _this['tableName'] = tableName;
  };

  /**
   * Constructs a <code>OLAPTable</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:client.model/OLAPTable} obj Optional instance to populate.
   * @return {module:client.model/OLAPTable} The populated <code>OLAPTable</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('collections')) {
        obj['collections'] = ApiClient.convertToType(data['collections'], ['String']);
      }
      if (data.hasOwnProperty('dimensions')) {
        obj['dimensions'] = ApiClient.convertToType(data['dimensions'], ['String']);
      }
      if (data.hasOwnProperty('aggregations')) {
        obj['aggregations'] = ApiClient.convertToType(data['aggregations'], ['String']);
      }
      if (data.hasOwnProperty('measures')) {
        obj['measures'] = ApiClient.convertToType(data['measures'], ['String']);
      }
      if (data.hasOwnProperty('tableName')) {
        obj['tableName'] = ApiClient.convertToType(data['tableName'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {Array.<String>} collections
   */
  exports.prototype['collections'] = undefined;
  /**
   * @member {Array.<String>} dimensions
   */
  exports.prototype['dimensions'] = undefined;
  /**
   * @member {Array.<module:client.model/OLAPTable.AggregationsEnum>} aggregations
   */
  exports.prototype['aggregations'] = undefined;
  /**
   * @member {Array.<String>} measures
   */
  exports.prototype['measures'] = undefined;
  /**
   * @member {String} tableName
   */
  exports.prototype['tableName'] = undefined;


  /**
   * Allowed values for the <code>aggregations</code> property.
   * @enum {String}
   * @readonly
   */
  exports.AggregationsEnum = {
    /**
     * value: "COUNT"
     * @const
     */
    "COUNT": "COUNT",
    /**
     * value: "COUNT_UNIQUE"
     * @const
     */
    "COUNT_UNIQUE": "COUNT_UNIQUE",
    /**
     * value: "SUM"
     * @const
     */
    "SUM": "SUM",
    /**
     * value: "MINIMUM"
     * @const
     */
    "MINIMUM": "MINIMUM",
    /**
     * value: "MAXIMUM"
     * @const
     */
    "MAXIMUM": "MAXIMUM",
    /**
     * value: "AVERAGE"
     * @const
     */
    "AVERAGE": "AVERAGE",
    /**
     * value: "APPROXIMATE_UNIQUE"
     * @const
     */
    "APPROXIMATE_UNIQUE": "APPROXIMATE_UNIQUE"  };


  return exports;
}));


