/**
 * Rakam API Documentation
 * An analytics platform API that lets you create your own analytics services.
 *
 * OpenAPI spec version: 0.5
 * Contact: contact@rakam.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'client.model/Measure'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Measure'));
  } else {
    // Browser globals (root is window)
    if (!root.RakamClient) {
      root.RakamClient = {};
    }
    root.RakamClient.RealtimeQueryTable = factory(root.RakamClient.ApiClient, root.RakamClient.Measure);
  }
}(this, function(ApiClient, Measure) {
  'use strict';




  /**
   * The RealtimeQueryTable model module.
   * @module client.model/RealtimeQueryTable
   * @version 0.5
   */

  /**
   * Constructs a new <code>RealtimeQueryTable</code>.
   * @alias module:client.model/RealtimeQueryTable
   * @class
   */
  var exports = function() {
    var _this = this;








  };

  /**
   * Constructs a <code>RealtimeQueryTable</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:client.model/RealtimeQueryTable} obj Optional instance to populate.
   * @return {module:client.model/RealtimeQueryTable} The populated <code>RealtimeQueryTable</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('table_name')) {
        obj['table_name'] = ApiClient.convertToType(data['table_name'], 'String');
      }
      if (data.hasOwnProperty('filter')) {
        obj['filter'] = ApiClient.convertToType(data['filter'], 'String');
      }
      if (data.hasOwnProperty('measure')) {
        obj['measure'] = Measure.constructFromObject(data['measure']);
      }
      if (data.hasOwnProperty('dimensions')) {
        obj['dimensions'] = ApiClient.convertToType(data['dimensions'], ['String']);
      }
      if (data.hasOwnProperty('aggregate')) {
        obj['aggregate'] = ApiClient.convertToType(data['aggregate'], 'Boolean');
      }
      if (data.hasOwnProperty('date_start')) {
        obj['date_start'] = ApiClient.convertToType(data['date_start'], 'Date');
      }
      if (data.hasOwnProperty('date_end')) {
        obj['date_end'] = ApiClient.convertToType(data['date_end'], 'Date');
      }
    }
    return obj;
  }

  /**
   * @member {String} table_name
   */
  exports.prototype['table_name'] = undefined;
  /**
   * @member {String} filter
   */
  exports.prototype['filter'] = undefined;
  /**
   * @member {module:client.model/Measure} measure
   */
  exports.prototype['measure'] = undefined;
  /**
   * @member {Array.<String>} dimensions
   */
  exports.prototype['dimensions'] = undefined;
  /**
   * @member {Boolean} aggregate
   */
  exports.prototype['aggregate'] = undefined;
  /**
   * @member {Date} date_start
   */
  exports.prototype['date_start'] = undefined;
  /**
   * @member {Date} date_end
   */
  exports.prototype['date_end'] = undefined;



  return exports;
}));


