/**
 * Rakam API Documentation
 * An analytics platform API that lets you create your own analytics services.
 *
 * OpenAPI spec version: 0.5
 * Contact: contact@rakam.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'client.model/CollectionDefinition', 'client.model/ContinuousQuery', 'client.model/MaterializedView'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./CollectionDefinition'), require('./ContinuousQuery'), require('./MaterializedView'));
  } else {
    // Browser globals (root is window)
    if (!root.RakamClient) {
      root.RakamClient = {};
    }
    root.RakamClient.Recipe = factory(root.RakamClient.ApiClient, root.RakamClient.CollectionDefinition, root.RakamClient.ContinuousQuery, root.RakamClient.MaterializedView);
  }
}(this, function(ApiClient, CollectionDefinition, ContinuousQuery, MaterializedView) {
  'use strict';




  /**
   * The Recipe model module.
   * @module client.model/Recipe
   * @version 0.5
   */

  /**
   * Constructs a new <code>Recipe</code>.
   * @alias module:client.model/Recipe
   * @class
   */
  var exports = function() {
    var _this = this;





  };

  /**
   * Constructs a <code>Recipe</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:client.model/Recipe} obj Optional instance to populate.
   * @return {module:client.model/Recipe} The populated <code>Recipe</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('strategy')) {
        obj['strategy'] = ApiClient.convertToType(data['strategy'], 'String');
      }
      if (data.hasOwnProperty('collections')) {
        obj['collections'] = ApiClient.convertToType(data['collections'], {'String': CollectionDefinition});
      }
      if (data.hasOwnProperty('materialized_views')) {
        obj['materialized_views'] = ApiClient.convertToType(data['materialized_views'], [MaterializedView]);
      }
      if (data.hasOwnProperty('continuous_queries')) {
        obj['continuous_queries'] = ApiClient.convertToType(data['continuous_queries'], [ContinuousQuery]);
      }
    }
    return obj;
  }

  /**
   * @member {module:client.model/Recipe.StrategyEnum} strategy
   */
  exports.prototype['strategy'] = undefined;
  /**
   * @member {Object.<String, module:client.model/CollectionDefinition>} collections
   */
  exports.prototype['collections'] = undefined;
  /**
   * @member {Array.<module:client.model/MaterializedView>} materialized_views
   */
  exports.prototype['materialized_views'] = undefined;
  /**
   * @member {Array.<module:client.model/ContinuousQuery>} continuous_queries
   */
  exports.prototype['continuous_queries'] = undefined;


  /**
   * Allowed values for the <code>strategy</code> property.
   * @enum {String}
   * @readonly
   */
  exports.StrategyEnum = {
    /**
     * value: "DEFAULT"
     * @const
     */
    "DEFAULT": "DEFAULT",
    /**
     * value: "SPECIFIC"
     * @const
     */
    "SPECIFIC": "SPECIFIC"  };


  return exports;
}));


