/**
 * Rakam API Documentation
 * An analytics platform API that lets you create your own analytics services.
 *
 * OpenAPI spec version: 0.5
 * Contact: contact@rakam.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'client.model/RetentionAction'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./RetentionAction'));
  } else {
    // Browser globals (root is window)
    if (!root.RakamClient) {
      root.RakamClient = {};
    }
    root.RakamClient.RetentionQuery = factory(root.RakamClient.ApiClient, root.RakamClient.RetentionAction);
  }
}(this, function(ApiClient, RetentionAction) {
  'use strict';




  /**
   * The RetentionQuery model module.
   * @module client.model/RetentionQuery
   * @version 0.5
   */

  /**
   * Constructs a new <code>RetentionQuery</code>.
   * @alias module:client.model/RetentionQuery
   * @class
   */
  var exports = function() {
    var _this = this;








  };

  /**
   * Constructs a <code>RetentionQuery</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:client.model/RetentionQuery} obj Optional instance to populate.
   * @return {module:client.model/RetentionQuery} The populated <code>RetentionQuery</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('first_action')) {
        obj['first_action'] = RetentionAction.constructFromObject(data['first_action']);
      }
      if (data.hasOwnProperty('returning_action')) {
        obj['returning_action'] = RetentionAction.constructFromObject(data['returning_action']);
      }
      if (data.hasOwnProperty('dimension')) {
        obj['dimension'] = ApiClient.convertToType(data['dimension'], 'String');
      }
      if (data.hasOwnProperty('date_unit')) {
        obj['date_unit'] = ApiClient.convertToType(data['date_unit'], 'String');
      }
      if (data.hasOwnProperty('period')) {
        obj['period'] = ApiClient.convertToType(data['period'], 'Integer');
      }
      if (data.hasOwnProperty('startDate')) {
        obj['startDate'] = ApiClient.convertToType(data['startDate'], 'Date');
      }
      if (data.hasOwnProperty('endDate')) {
        obj['endDate'] = ApiClient.convertToType(data['endDate'], 'Date');
      }
    }
    return obj;
  }

  /**
   * @member {module:client.model/RetentionAction} first_action
   */
  exports.prototype['first_action'] = undefined;
  /**
   * @member {module:client.model/RetentionAction} returning_action
   */
  exports.prototype['returning_action'] = undefined;
  /**
   * @member {String} dimension
   */
  exports.prototype['dimension'] = undefined;
  /**
   * @member {module:client.model/RetentionQuery.DateUnitEnum} date_unit
   */
  exports.prototype['date_unit'] = undefined;
  /**
   * @member {Integer} period
   */
  exports.prototype['period'] = undefined;
  /**
   * @member {Date} startDate
   */
  exports.prototype['startDate'] = undefined;
  /**
   * @member {Date} endDate
   */
  exports.prototype['endDate'] = undefined;


  /**
   * Allowed values for the <code>date_unit</code> property.
   * @enum {String}
   * @readonly
   */
  exports.DateUnitEnum = {
    /**
     * value: "DAY"
     * @const
     */
    "DAY": "DAY",
    /**
     * value: "WEEK"
     * @const
     */
    "WEEK": "WEEK",
    /**
     * value: "MONTH"
     * @const
     */
    "MONTH": "MONTH"  };


  return exports;
}));


