/**
 * Rakam API Documentation
 * An analytics platform API that lets you create your own analytics services.
 *
 * OpenAPI spec version: 0.5
 * Contact: contact@rakam.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'client.model/QueryResult', 'client.model/ErrorMessage', 'client.model/FunnelQuery'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../client.model/QueryResult'), require('../client.model/ErrorMessage'), require('../client.model/FunnelQuery'));
  } else {
    // Browser globals (root is window)
    if (!root.RakamClient) {
      root.RakamClient = {};
    }
    root.RakamClient.FunnelApi = factory(root.RakamClient.ApiClient, root.RakamClient.QueryResult, root.RakamClient.ErrorMessage, root.RakamClient.FunnelQuery);
  }
}(this, function(ApiClient, QueryResult, ErrorMessage, FunnelQuery) {
  'use strict';

  /**
   * Funnel service.
   * @module client.api/FunnelApi
   * @version 0.5
   */

  /**
   * Constructs a new FunnelApi. 
   * @alias module:client.api/FunnelApi
   * @class
   * @param {module:ApiClient} apiClient Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the analyzeFunnel operation.
     * @callback module:client.api/FunnelApi~analyzeFunnelCallback
     * @param {String} error Error message, if any.
     * @param {module:client.model/QueryResult} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Execute query
     * 
     * @param {module:client.model/FunnelQuery} funnelQuery 
     * @param {module:client.api/FunnelApi~analyzeFunnelCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {module:client.model/QueryResult}
     */
    this.analyzeFunnel = function(funnelQuery, callback) {
      var postBody = funnelQuery;

      // verify the required parameter 'funnelQuery' is set
      if (funnelQuery == undefined || funnelQuery == null) {
        throw "Missing the required parameter 'funnelQuery' when calling analyzeFunnel";
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['read_key'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = QueryResult;

      return this.apiClient.callApi(
        '/funnel/analyze', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
