/**
 * Rakam API Documentation
 * An analytics platform API that lets you create your own analytics services.
 *
 * OpenAPI spec version: 0.5
 * Contact: contact@rakam.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'client.model/SuccessMessage', 'client.model/RealTimeReport', 'client.model/ErrorMessage', 'client.model/RealtimeDeleteTable', 'client.model/ContinuousQuery', 'client.model/RealtimeQueryTable', 'client.model/RealTimeQueryResult'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../client.model/SuccessMessage'), require('../client.model/RealTimeReport'), require('../client.model/ErrorMessage'), require('../client.model/RealtimeDeleteTable'), require('../client.model/ContinuousQuery'), require('../client.model/RealtimeQueryTable'), require('../client.model/RealTimeQueryResult'));
  } else {
    // Browser globals (root is window)
    if (!root.RakamClient) {
      root.RakamClient = {};
    }
    root.RakamClient.RealtimeApi = factory(root.RakamClient.ApiClient, root.RakamClient.SuccessMessage, root.RakamClient.RealTimeReport, root.RakamClient.ErrorMessage, root.RakamClient.RealtimeDeleteTable, root.RakamClient.ContinuousQuery, root.RakamClient.RealtimeQueryTable, root.RakamClient.RealTimeQueryResult);
  }
}(this, function(ApiClient, SuccessMessage, RealTimeReport, ErrorMessage, RealtimeDeleteTable, ContinuousQuery, RealtimeQueryTable, RealTimeQueryResult) {
  'use strict';

  /**
   * Realtime service.
   * @module client.api/RealtimeApi
   * @version 0.5
   */

  /**
   * Constructs a new RealtimeApi. 
   * @alias module:client.api/RealtimeApi
   * @class
   * @param {module:ApiClient} apiClient Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the createTable operation.
     * @callback module:client.api/RealtimeApi~createTableCallback
     * @param {String} error Error message, if any.
     * @param {module:client.model/SuccessMessage} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create report
     * 
     * @param {module:client.model/RealTimeReport} realTimeReport 
     * @param {module:client.api/RealtimeApi~createTableCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {module:client.model/SuccessMessage}
     */
    this.createTable = function(realTimeReport, callback) {
      var postBody = realTimeReport;

      // verify the required parameter 'realTimeReport' is set
      if (realTimeReport == undefined || realTimeReport == null) {
        throw "Missing the required parameter 'realTimeReport' when calling createTable";
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['master_key'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = SuccessMessage;

      return this.apiClient.callApi(
        '/realtime/create', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the deleteTable operation.
     * @callback module:client.api/RealtimeApi~deleteTableCallback
     * @param {String} error Error message, if any.
     * @param {module:client.model/SuccessMessage} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete report
     * 
     * @param {module:client.model/RealtimeDeleteTable} realtimeDeleteTable 
     * @param {module:client.api/RealtimeApi~deleteTableCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {module:client.model/SuccessMessage}
     */
    this.deleteTable = function(realtimeDeleteTable, callback) {
      var postBody = realtimeDeleteTable;

      // verify the required parameter 'realtimeDeleteTable' is set
      if (realtimeDeleteTable == undefined || realtimeDeleteTable == null) {
        throw "Missing the required parameter 'realtimeDeleteTable' when calling deleteTable";
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['master_key'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = SuccessMessage;

      return this.apiClient.callApi(
        '/realtime/delete', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the listTables operation.
     * @callback module:client.api/RealtimeApi~listTablesCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:client.model/ContinuousQuery>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * List queries
     * 
     * @param {module:client.api/RealtimeApi~listTablesCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {Array.<module:client.model/ContinuousQuery>}
     */
    this.listTables = function(callback) {
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['read_key'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = [ContinuousQuery];

      return this.apiClient.callApi(
        '/realtime/list', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the queryTable operation.
     * @callback module:client.api/RealtimeApi~queryTableCallback
     * @param {String} error Error message, if any.
     * @param {module:client.model/RealTimeQueryResult} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get report
     * 
     * @param {module:client.model/RealtimeQueryTable} realtimeQueryTable 
     * @param {module:client.api/RealtimeApi~queryTableCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {module:client.model/RealTimeQueryResult}
     */
    this.queryTable = function(realtimeQueryTable, callback) {
      var postBody = realtimeQueryTable;

      // verify the required parameter 'realtimeQueryTable' is set
      if (realtimeQueryTable == undefined || realtimeQueryTable == null) {
        throw "Missing the required parameter 'realtimeQueryTable' when calling queryTable";
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['read_key'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = RealTimeQueryResult;

      return this.apiClient.callApi(
        '/realtime/get', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
