/**
 * Rakam API Documentation
 * An analytics platform API that lets you create your own analytics services.
 *
 * OpenAPI spec version: 0.5
 * Contact: contact@rakam.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'client.model/Recipe', 'client.model/ErrorMessage', 'client.model/SuccessMessage'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../client.model/Recipe'), require('../client.model/ErrorMessage'), require('../client.model/SuccessMessage'));
  } else {
    // Browser globals (root is window)
    if (!root.RakamClient) {
      root.RakamClient = {};
    }
    root.RakamClient.RecipeApi = factory(root.RakamClient.ApiClient, root.RakamClient.Recipe, root.RakamClient.ErrorMessage, root.RakamClient.SuccessMessage);
  }
}(this, function(ApiClient, Recipe, ErrorMessage, SuccessMessage) {
  'use strict';

  /**
   * Recipe service.
   * @module client.api/RecipeApi
   * @version 0.5
   */

  /**
   * Constructs a new RecipeApi. 
   * @alias module:client.api/RecipeApi
   * @class
   * @param {module:ApiClient} apiClient Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the exportRecipe operation.
     * @callback module:client.api/RecipeApi~exportRecipeCallback
     * @param {String} error Error message, if any.
     * @param {module:client.model/Recipe} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Export recipe
     * 
     * @param {module:client.model/String} accept 
     * @param {module:client.api/RecipeApi~exportRecipeCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {module:client.model/Recipe}
     */
    this.exportRecipe = function(accept, callback) {
      var postBody = null;

      // verify the required parameter 'accept' is set
      if (accept == undefined || accept == null) {
        throw "Missing the required parameter 'accept' when calling exportRecipe";
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var headerParams = {
        'Accept': accept
      };
      var formParams = {
      };

      var authNames = ['master_key'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = Recipe;

      return this.apiClient.callApi(
        '/recipe/export', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the installRecipe operation.
     * @callback module:client.api/RecipeApi~installRecipeCallback
     * @param {String} error Error message, if any.
     * @param {module:client.model/SuccessMessage} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Install recipe
     * 
     * @param {module:client.api/RecipeApi~installRecipeCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {module:client.model/SuccessMessage}
     */
    this.installRecipe = function(callback) {
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['master_key'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = SuccessMessage;

      return this.apiClient.callApi(
        '/recipe/install', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
