/**
 * Rakam API Documentation
 * An analytics platform API that lets you create your own analytics services.
 *
 * OpenAPI spec version: 0.5
 * Contact: contact@rakam.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'client.model/ErrorMessage', 'client.model/UserEmailActionBatch', 'client.model/UserEmailActionSend'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../client.model/ErrorMessage'), require('../client.model/UserEmailActionBatch'), require('../client.model/UserEmailActionSend'));
  } else {
    // Browser globals (root is window)
    if (!root.RakamClient) {
      root.RakamClient = {};
    }
    root.RakamClient.UseractionApi = factory(root.RakamClient.ApiClient, root.RakamClient.ErrorMessage, root.RakamClient.UserEmailActionBatch, root.RakamClient.UserEmailActionSend);
  }
}(this, function(ApiClient, ErrorMessage, UserEmailActionBatch, UserEmailActionSend) {
  'use strict';

  /**
   * Useraction service.
   * @module client.api/UseractionApi
   * @version 0.5
   */

  /**
   * Constructs a new UseractionApi. 
   * @alias module:client.api/UseractionApi
   * @class
   * @param {module:ApiClient} apiClient Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the batch operation.
     * @callback module:client.api/UseractionApi~batchCallback
     * @param {String} error Error message, if any.
     * @param {'Integer'} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Apply batch operation
     * 
     * @param {module:client.model/UserEmailActionBatch} userEmailActionBatch 
     * @param {module:client.api/UseractionApi~batchCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {'Integer'}
     */
    this.batch = function(userEmailActionBatch, callback) {
      var postBody = userEmailActionBatch;

      // verify the required parameter 'userEmailActionBatch' is set
      if (userEmailActionBatch == undefined || userEmailActionBatch == null) {
        throw "Missing the required parameter 'userEmailActionBatch' when calling batch";
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['read_key'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = 'Integer';

      return this.apiClient.callApi(
        '/user/action/email/batch', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the send operation.
     * @callback module:client.api/UseractionApi~sendCallback
     * @param {String} error Error message, if any.
     * @param {'Boolean'} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Perform action for single user
     * 
     * @param {module:client.model/UserEmailActionSend} userEmailActionSend 
     * @param {module:client.api/UseractionApi~sendCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {'Boolean'}
     */
    this.send = function(userEmailActionSend, callback) {
      var postBody = userEmailActionSend;

      // verify the required parameter 'userEmailActionSend' is set
      if (userEmailActionSend == undefined || userEmailActionSend == null) {
        throw "Missing the required parameter 'userEmailActionSend' when calling send";
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['read_key'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = 'Boolean';

      return this.apiClient.callApi(
        '/user/action/email/single', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
